### PR TITLE
Update dcg_controller.py

### PR DESCRIPTION
**Pull request by Nikunj-Gupta**

### CODE REVIEW

**Comment by wendelinboehmer** [comment]
This change does not seem to make sense: cloning preserved gradient flow, so this clone just duplicates a tensor and then keeps the duplicate.

**Comment by Nikunj-Gupta** [comment]
I am running into the following error otherwise 

```
 output[1] = output[1].transpose(dim0=-2, dim1=-1)
    ~~~~~~^^^
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```

**Review by wendelinboehmer — APPROVED** [review]

**Comment by wendelinboehmer** [comment]
Another change in the API. ;)

**Comment by Nikunj-Gupta** [comment]
:D

**Pull request merged**
